import { useState } from 'react';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Link } from 'react-router-dom';
import { 
  Clock, 
  Users, 
  Target, 
  Brain, 
  Headphones, 
  BookOpen, 
  PenTool, 
  Mic,
  Play,
  CheckCircle,
  ArrowRight,
  Zap
} from 'lucide-react';

const MockTests = () => {
  const [selectedTest, setSelectedTest] = useState<string | null>(null);

  const testTypes = [
    {
      id: 'listening',
      icon: Headphones,
      title: 'Listening Test',
      duration: '30 minutes',
      questions: '40 questions',
      description: 'Practice with authentic IELTS listening materials featuring various accents and contexts.',
      features: ['Multiple accents', 'Real exam format', 'AI feedback', 'Score prediction']
    },
    {
      id: 'reading',
      icon: BookOpen,
      title: 'Reading Test',
      duration: '60 minutes',
      questions: '40 questions',
      description: 'Academic and General Training reading passages with AI-powered comprehension analysis.',
      features: ['Academic texts', 'Time management', 'Vocabulary analysis', 'Strategy tips']
    },
    {
      id: 'writing',
      icon: PenTool,
      title: 'Writing Test',
      duration: '60 minutes',
      questions: '2 tasks',
      description: 'Practice both Task 1 and Task 2 with detailed AI feedback on all assessment criteria.',
      features: ['Task achievement', 'Coherence analysis', 'Grammar check', 'Band scoring']
    },
    {
      id: 'speaking',
      icon: Mic,
      title: 'Speaking Test',
      duration: '15 minutes',
      questions: '3 parts',
      description: 'Interactive speaking practice with AI that evaluates fluency, pronunciation, and vocabulary.',
      features: ['Real-time evaluation', 'Pronunciation help', 'Fluency analysis', 'Part-specific feedback']
    }
  ];

  const mockExamFeatures = [
    {
      icon: Brain,
      title: 'AI-Generated Questions',
      description: 'Unique questions generated by AI based on official IELTS patterns and difficulty levels.'
    },
    {
      icon: Target,
      title: 'Accurate Scoring',
      description: 'Precise band score predictions using machine learning models trained on thousands of responses.'
    },
    {
      icon: Clock,
      title: 'Timed Practice',
      description: 'Realistic exam conditions with proper timing to help you manage time effectively during the real test.'
    },
    {
      icon: Users,
      title: 'Performance Analytics',
      description: 'Detailed analysis of your strengths and weaknesses with personalized improvement recommendations.'
    }
  ];

  return (
    <div className="min-h-screen pt-24">
      {/* Hero Section */}
      <section className="py-20 bg-gradient-subtle">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 text-center">
          <div className="inline-flex items-center px-4 py-2 bg-primary/10 border border-primary/20 rounded-full text-primary text-sm font-medium mb-8">
            <Zap className="w-4 h-4 mr-2" />
            AI-Generated Mock Exams
          </div>
          <h1 className="text-5xl font-bold text-foreground mb-6">
            IELTS Mock Tests
            <span className="bg-gradient-primary bg-clip-text text-transparent"> Powered by AI</span>
          </h1>
          <p className="text-xl text-muted-foreground max-w-3xl mx-auto mb-8">
            Experience realistic IELTS mock exams with AI-generated questions that adapt to official test patterns. 
            Get instant feedback and detailed performance analysis to maximize your preparation.
          </p>
          <Link to="/signup">
            <Button variant="premium" size="lg">
              Start Mock Test Now
              <Play className="w-5 h-5 ml-2" />
            </Button>
          </Link>
        </div>
      </section>

      {/* How AI Mock Tests Work */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-foreground mb-4">
              How Our AI-Generated Mock Exams Work
            </h2>
            <p className="text-xl text-muted-foreground max-w-3xl mx-auto">
              Our advanced AI system creates authentic IELTS questions that mirror the real exam experience, 
              providing you with unlimited practice opportunities.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            {mockExamFeatures.map((feature, index) => (
              <Card key={index} className="p-6 bg-gradient-card border-card-border hover:shadow-medium transition-all duration-300">
                <div className="w-12 h-12 bg-gradient-primary rounded-xl flex items-center justify-center mb-4">
                  <feature.icon className="w-6 h-6 text-white" />
                </div>
                <h3 className="text-xl font-semibold text-foreground mb-2">{feature.title}</h3>
                <p className="text-muted-foreground">{feature.description}</p>
              </Card>
            ))}
          </div>
        </div>
      </section>

      {/* Test Categories */}
      <section className="py-20 bg-gradient-subtle">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="text-center mb-16">
            <h2 className="text-4xl font-bold text-foreground mb-4">
              Choose Your Test Category
            </h2>
            <p className="text-xl text-muted-foreground max-w-2xl mx-auto">
              Practice individual skills or take a complete mock exam. Each test provides detailed AI feedback 
              and personalized improvement suggestions.
            </p>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
            {testTypes.map((test) => (
              <Card 
                key={test.id} 
                className={`p-8 bg-gradient-card border-card-border transition-all duration-300 cursor-pointer ${
                  selectedTest === test.id ? 'shadow-large border-primary' : 'hover:shadow-medium'
                }`}
                onClick={() => setSelectedTest(test.id)}
              >
                <div className="flex items-start space-x-4 mb-6">
                  <div className="w-16 h-16 bg-gradient-primary rounded-xl flex items-center justify-center shrink-0">
                    <test.icon className="w-8 h-8 text-white" />
                  </div>
                  <div className="flex-1">
                    <h3 className="text-2xl font-bold text-foreground mb-2">{test.title}</h3>
                    <div className="flex items-center space-x-4 text-sm text-muted-foreground mb-3">
                      <span className="flex items-center">
                        <Clock className="w-4 h-4 mr-1" />
                        {test.duration}
                      </span>
                      <span>{test.questions}</span>
                    </div>
                    <p className="text-muted-foreground">{test.description}</p>
                  </div>
                </div>

                <div className="space-y-2 mb-6">
                  {test.features.map((feature, index) => (
                    <div key={index} className="flex items-center space-x-2">
                      <CheckCircle className="w-4 h-4 text-success" />
                      <span className="text-sm text-foreground">{feature}</span>
                    </div>
                  ))}
                </div>

                <Button 
                  variant={selectedTest === test.id ? "hero" : "outline"} 
                  className="w-full"
                >
                  Start {test.title}
                  <ArrowRight className="w-4 h-4 ml-2" />
                </Button>
              </Card>
            ))}
          </div>

          {/* Full Mock Exam */}
          <div className="mt-12">
            <Card className="p-8 bg-gradient-primary text-white border-0">
              <div className="text-center">
                <h3 className="text-3xl font-bold mb-4">Complete IELTS Mock Exam</h3>
                <p className="text-xl text-white/90 mb-6 max-w-2xl mx-auto">
                  Take a full 3-hour IELTS simulation with all four skills. Get comprehensive AI analysis 
                  and an overall band score prediction.
                </p>
                <div className="flex flex-col sm:flex-row gap-4 justify-center">
                  <Button variant="secondary" size="lg">
                    Academic Test (3 hours)
                  </Button>
                  <Button variant="secondary" size="lg">
                    General Training (3 hours)
                  </Button>
                </div>
              </div>
            </Card>
          </div>
        </div>
      </section>

      {/* Test Preparation Tips */}
      <section className="py-20">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
          <div className="grid grid-cols-1 lg:grid-cols-2 gap-16 items-center">
            <div>
              <h2 className="text-4xl font-bold text-foreground mb-6">
                Maximize Your Mock Test Results
              </h2>
              <p className="text-xl text-muted-foreground mb-8">
                Get the most out of your practice sessions with our AI-powered analysis and expert tips.
              </p>
              <div className="space-y-6">
                {[
                  {
                    title: "Simulate Real Conditions",
                    description: "Take tests in a quiet environment with proper timing to replicate exam conditions."
                  },
                  {
                    title: "Review AI Feedback",
                    description: "Carefully analyze the detailed feedback to understand your mistakes and learn from them."
                  },
                  {
                    title: "Track Your Progress",
                    description: "Regular practice with our analytics helps identify improvement patterns over time."
                  },
                  {
                    title: "Focus on Weak Areas",
                    description: "Use AI recommendations to prioritize practice in areas where you need the most improvement."
                  }
                ].map((tip, index) => (
                  <div key={index} className="flex items-start space-x-4">
                    <div className="w-8 h-8 bg-gradient-primary rounded-full flex items-center justify-center shrink-0 mt-1">
                      <span className="text-white text-sm font-bold">{index + 1}</span>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-foreground mb-1">{tip.title}</h3>
                      <p className="text-muted-foreground">{tip.description}</p>
                    </div>
                  </div>
                ))}
              </div>
            </div>
            <div className="bg-gradient-card rounded-3xl p-8 border border-card-border shadow-large">
              <h3 className="text-2xl font-bold text-foreground mb-6 text-center">
                Ready to Test Your Skills?
              </h3>
              <div className="space-y-4">
                <div className="bg-primary/10 rounded-xl p-4 text-center">
                  <div className="text-3xl font-bold text-primary mb-2">7 Days Free</div>
                  <div className="text-sm text-muted-foreground">Unlimited mock tests</div>
                </div>
                <Link to="/signup">
                  <Button variant="hero" size="lg" className="w-full">
                    Generate Your First Mock Exam
                    <ArrowRight className="w-5 h-5 ml-2" />
                  </Button>
                </Link>
                <p className="text-xs text-muted-foreground text-center">
                  No credit card required • Instant access
                </p>
              </div>
            </div>
          </div>
        </div>
      </section>
    </div>
  );
};

export default MockTests;